name: CI

on: 
  push:
    branches:
      - version-3

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_versions: [10.x]

    steps:
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        node_version: '10.x'
        build_dir: build/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
